version: '3.9'
services:
  app:
    build: 
      context: ./app
      dockerfile: Dockerfile
    image: expenses-manager-app
    container_name: expenses-manager-app
    volumes:
      - ./app:/expenses-manager/app
      - /expenses-manager/app/node_modules
    stdin_open : true
    tty: true
    depends_on:
      - backend
    networks:
      - expenses-manager-app-network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    image: expenses-manager-backend
    container_name:  expenses-manager-backend
    restart: always
    volumes:
      - ./backend:/expenses-manager/backend
      - /expenses-manager/backend/node_modules
    ports:
      - 3000:3000
    depends_on:
      - database
    networks:
      - expenses-manager-app-network
  
  database:
    image: mongo
    container_name: expenses-manager-mongodb
    ports:
      - 27017:27017
    volumes:
      - ./database:/data/db
    networks:
      - expenses-manager-app-network

networks:
  expenses-manager-app-network:
    driver: bridge

volumes:
  node_modules:    