FROM node:18

# Install ffmpeg inside the container
RUN apt-get update && apt-get install -y ffmpeg

WORKDIR /expenses-manager/dev/backend

COPY backend/package*.json ./

COPY backend/ ./

RUN npm install -f

EXPOSE 3100

CMD ["npm","run","dev"]
