FROM node:18

# Install ffmpeg inside the container
RUN apt-get update && apt-get install -y ffmpeg

WORKDIR /expenses-manager/prod/backend

COPY backend/package*.json ./

COPY backend/ ./

RUN npm install -f

EXPOSE 3000

CMD ["npm","run","prod"]
 