# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

lane :show_version do
  version = get_version_name(app_project_dir: '**/app')
  UI.message("Default: #{version}")
  version_code = get_version_code(app_project_dir: '**/app')
  UI.message("Default Code: #{version_code}")
end


lane :bumpup do
  increment_version_name(app_project_dir: '**/app', bump_type: 'patch')
  increment_version_code(app_project_dir: '**/app')
end

platform :android do
  desc "Deploy to internal testing track"
  lane :internal do

    show_version
    bumpup
    gradle(
      task:"bundle",
      build_type: "Release"
    )
    upload_to_play_store(
      track: 'internal',
      aab: 'app/build/outputs/bundle/release/app-release.aab',
      skip_upload_apk: true,  
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end

  desc "Deploy to production"
  lane :production do
    show_version
    bumpup
    gradle(
      task: "bundle",
      build_type: "Release"
    )
    upload_to_play_store(
      track: 'production',
      aab: 'app/build/outputs/bundle/release/app-release.aab',
      skip_upload_apk: true,  
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end

end
