# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do

    match(
      type: "appstore",
      app_identifier: [
        "com.webwizard.expensesmanager",
        "com.webwizard.expensesmanager.OneSignalNotificationServiceExtension"
      ]
    )

    increment_build_number(xcodeproj: "expensesmanager.xcodeproj")

    build_app(
      workspace: "expensesmanager.xcworkspace",
      scheme: "expensesmanager",
      export_method: "app-store",
      clean: true
    )

    upload_to_testflight(
      api_key: {
          key_id: "U234N7PWX5",
          issuer_id: "97d75142-ea8c-43f3-a3b5-a869dc575906",
          key: File.read("../AuthKey_U234N7PWX5_Fastlane.p8"),
          in_house: false
      },
      skip_waiting_for_build_processing: false
    )
  end

  desc "Deploy a release build to App Store"
  lane :release do
    match(
      type: "appstore",
      app_identifier: [
        "com.webwizard.expensesmanager",
        "com.webwizard.expensesmanager.OneSignalNotificationServiceExtension"
      ]
    )

    increment_build_number(xcodeproj: "expensesmanager.xcodeproj")

    build_app(
      workspace: "expensesmanager.xcworkspace",
      scheme: "expensesmanager",
      export_method: "app-store",
      clean: true
    )

    deliver(
      api_key: {
        key_id: "U234N7PWX5",
        issuer_id: "97d75142-ea8c-43f3-a3b5-a869dc575906",
        key: File.read("../AuthKey_U234N7PWX5_Fastlane.p8"),
        in_house: false
      },
      submit_for_review: true,
      automatic_release: false, # set to true if you want it auto-live
      force: true
    )
  end
end