name: Setup GPG and Unlock Key
description: Imports GPG key and unlocks it for use in the current job

inputs:
  gpg_key_email:
    required: true
  gpg_private_key:
    required: true
  gpg_passphrase:
    required: true

runs:
  using: "composite"
  steps:
    - run: |
        export GPG_TTY=$(tty)
        export SOPS_GPG_EXEC=gpg
        export TERM=xterm-256color

        mkdir -p ~/.gnupg
        chmod 700 ~/.gnupg

        echo "allow-loopback-pinentry" >> ~/.gnupg/gpg-agent.conf
        echo "pinentry-mode loopback" >> ~/.gnupg/gpg.conf

        echo "${{ inputs.gpg_private_key }}" | base64 -d > private.key
        echo "${{ inputs.gpg_passphrase }}" | \
          gpg --batch --yes --pinentry-mode loopback --passphrase-fd 0 --import private.key

        gpg --with-colons --fingerprint | awk -F: '/^fpr:/ {print $10 ":6:"}' | \
          gpg --import-ownertrust

        echo "unlock" | \
          gpg --batch --yes --pinentry-mode loopback --passphrase "${{ inputs.gpg_passphrase }}" \
          -e -r "${{ inputs.gpg_key_email }}" | \
          gpg --batch --yes --pinentry-mode loopback --passphrase "${{ inputs.gpg_passphrase }}" -d

        rm private.key
      shell: bash
