name: Web Dev CI/CD

on:
  push:
    branches: [development]

jobs:
  setup-and-decrypt:
    uses: ./.github/workflows/setup-gpg.yml
    with:
      gpg_key_email: "sunil.pandvd22@gmail.com"
    secrets:
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

  build-and-deploy:
    needs: setup-and-decrypt
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Decrypt .env.development.enc
        run: |
          export GPG_TTY=$(tty)
          export SOPS_GPG_EXEC=gpg
          sops -d web/.env.development.enc > web/.env.development

      - name: Install dependencies
        run: |
          cd web
          npm install -f

      - name: Build the frontend (dev)
        run: |
          cd web
          npm run build:dev

      - name: Upload built frontend to VPS (development site)
        run: |
          sshpass -p "${{ secrets.PASS_WORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.HOST_NAME }} "rm -rf /var/www/dev.expensesmanager.app/*"
          sshpass -p "${{ secrets.PASS_WORD }}" scp -r web/dist/dev/* ${{ secrets.HOST_NAME }}:/var/www/dev.expensesmanager.app/

      - name: Upload graphics folder to VPS
        run: |
          sshpass -p "${{ secrets.PASS_WORD }}" scp -r graphics ${{ secrets.HOST_NAME }}:/var/www/dev.expensesmanager.app/
