name: Web Prod CI/CD

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install SOPS
        run: |
          sudo apt-get install -y gnupg
          wget https://github.com/getsops/sops/releases/download/v3.7.3/sops-v3.7.3.linux -O sops
          chmod +x sops
          sudo mv sops /usr/local/bin/sops

      - name: Setup GPG and Unlock Key
        uses: ./.github/actions/setup-gpg
        with:
          gpg_key_email: "sunil.pandvd22@gmail.com"
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Decrypt .env.production.enc
        run: |
          export GPG_TTY=$(tty)
          export SOPS_GPG_EXEC=gpg
          sops -d web/.env.production.enc > web/.env.production

      - name: Install dependencies
        run: |
          cd web
          npm install -f

      - name: Build the frontend (prod)
        run: |
          cd web
          npm run build:prod

      - name: Upload built frontend to VPS (production site)
        run: |
          sshpass -p "${{ secrets.PASS_WORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.HOST_NAME }} "rm -rf /var/www/expensesmanager.app/*"
          sshpass -p "${{ secrets.PASS_WORD }}" scp -r web/dist/prod/* ${{ secrets.HOST_NAME }}:/var/www/expensesmanager.app/

      - name: Upload graphics folder to VPS
        run: |
          sshpass -p "${{ secrets.PASS_WORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.HOST_NAME }} "mkdir -p /var/www/dev.expensesmanager.app/graphics"
          sshpass -p "${{ secrets.PASS_WORD }}" scp -r graphics/* ${{ secrets.HOST_NAME }}:/var/www/dev.expensesmanager.app/graphics/
