name: Backend Prod CI/CD

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install SOPS
        run: |
          sudo apt-get install -y gnupg
          wget https://github.com/getsops/sops/releases/download/v3.7.3/sops-v3.7.3.linux -O sops
          chmod +x sops
          sudo mv sops /usr/local/bin/sops

      - name: Setup GPG and Unlock Key
        uses: ./.github/actions/setup-gpg
        with:
          gpg_key_email: "sunil.pandvd22@gmail.com"
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Decrypt .env.production.enc using SOPS
        run: |
          export SOPS_GPG_EXEC=gpg
          export GPG_TTY=$(tty)
          sops -d backend/config/.env.production.enc > backend/config/.env.production

      - name: Decrypt expensesmanager.json using SOPS
        run: |
          export SOPS_GPG_EXEC=gpg
          export GPG_TTY=$(tty)
          sops -d backend/config/expensesmanager.json.enc | base64 -d > backend/config/expensesmanager.json

      - name: Upload .env.production to VPS
        run: |
          sshpass -p "${{ secrets.PASS_WORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.HOST_NAME }} "mkdir -p /expenses-manager/prod/backend/config"
          sshpass -p "${{ secrets.PASS_WORD }}" scp -o StrictHostKeyChecking=no backend/config/.env.production ${{ secrets.HOST_NAME }}:/expenses-manager/prod/backend/config/.env.production

      - name: Upload expensesmanager.json to VPS
        run: |
          sshpass -p "${{ secrets.PASS_WORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.HOST_NAME }} "mkdir -p /expenses-manager/prod/backend/config"
          sshpass -p "${{ secrets.PASS_WORD }}" scp backend/config/expensesmanager.json ${{ secrets.HOST_NAME }}:/expenses-manager/prod/backend/config/expensesmanager.json

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build Docker image (prod)
        run: docker build -f backend/Dockerfile.prod -t expenses-manager-backend-prod .

      - name: Tag Docker image
        run: docker tag expenses-manager-backend-prod sunilpasupuleti/expenses-manager-backend-prod:latest

      - name: Push image to Docker Hub
        run: docker push sunilpasupuleti/expenses-manager-backend-prod:latest

      - name: Clean up decrypted files
        run: |
          rm backend/config/.env.production
          rm backend/config/expensesmanager.json
